theme: jekyll-theme-cayman
title: Hannah's page
description: Website project for Computers and Language
github:
  page2: page2.html
  page3: page3.html
  page4: page4.html
  exercises: exercises.html
